using System.Text;

namespace ProtoLang.Tests.Performance;

/// <summary>
/// The larger half of the fixed corpus #57 measures against, and the code that produces it.
/// </summary>
/// <remarks>
/// <para>
/// <b>Generated, and committed anyway.</b> #57 asks for a corpus that is fixed and representative,
/// and those pull in opposite directions above a certain size: a file somebody typed stays honest
/// and stops growing, and a file generated at measurement time can be raised later but is a
/// different file every time the generator is touched -- so two runs a month apart would not be
/// comparable, which is the whole point of writing numbers down. Committing the output settles it.
/// The file is the corpus; this is how it got there and how it is raised.
/// </para>
/// <para>
/// <b>Which is why the committed copy is checked rather than trusted.</b>
/// <c>PerformanceCorpusTests.TheCommittedStressFileIsWhatTheGeneratorProduces</c> runs on every
/// build. Without it the two drift the first time somebody edits one of them, and a measurement
/// taken against a corpus nobody can reproduce is an anecdote.
/// </para>
/// <para>
/// <b>What it is shaped to stress, deliberately rather than by being large.</b> Size alone measures
/// the parser. The operations in #57's table are bounded by different things, so the file carries
/// one of each: <see cref="Steps"/> methods for the breadth of a scope a completion has to gather;
/// a single method called from every one of them, for the length of the list occurrence
/// highlighting walks; and one body of <see cref="Locals"/> locals, for a scope deep in declarations
/// rather than wide in members. A file that was merely long would say nothing about any of them.
/// </para>
/// <para>
/// Newlines are written as <c>\n</c> explicitly rather than through <c>Environment.NewLine</c>,
/// because the committed file is LF on every machine and a generator that emitted CRLF on Windows
/// would fail its own comparison there and nowhere else. That failure has already happened once in
/// this repository, to test fixtures rather than to this, and <c>.gitattributes</c> says so.
/// </para>
/// </remarks>
internal static class StressCorpus
{
    /// <summary>How many generated methods share one receiver.</summary>
    /// <remarks>
    /// Chosen so the file lands near three thousand lines -- an order of magnitude above
    /// <c>examples/simpleScript.protolang</c>, which is the normal case at 274. Raising it is the
    /// intended way to ask what happens at scale, and the committed file has to be rewritten from
    /// the generator when it moves.
    /// </remarks>
    public const int Steps = 170;

    /// <summary>How many locals the one deliberately deep body declares.</summary>
    public const int Locals = 60;

    /// <summary>The method every generated body calls, so that one symbol has many references.</summary>
    public const string Shared = "base_cents";

    /// <summary>The file's name in the corpus directory.</summary>
    public const string FileName = "wide.protolang";

    /// <summary>Where the committed copy lives.</summary>
    public static string Path { get; } =
        System.IO.Path.Combine(TestPaths.RepositoryRoot, "tests", "perf", "corpus", FileName);

    /// <summary>The committed copy, read from disk.</summary>
    /// <remarks>
    /// Read rather than generated, so a measurement is taken against the bytes in the repository
    /// and not against whatever this class would produce today. Behind a <see cref="Lazy{T}"/> and
    /// not a field initializer, because the file is absent for exactly as long as it takes to write
    /// it the first time, and a type initializer that throws there would take the generator down
    /// with it.
    /// </remarks>
    public static string Text => _text.Value;

    private static readonly Lazy<string> _text = new(() => File.ReadAllText(Path));

    /// <summary>The text the committed file is required to hold.</summary>
    public static string Generate()
    {
        var source = new StringBuilder();

        Preamble(source);
        Receiver(source);
        Aggregate(source);

        return source.ToString();
    }

    private static void Preamble(StringBuilder source)
    {
        Line(source, "// Generated by StressCorpus.Generate(). Do not edit by hand.");
        Line(source, "//");
        Line(source, "// The large half of the fixed corpus the performance budgets are measured against; the");
        Line(source, "// normal half is examples/simpleScript.protolang. See docs/performance.md for what each");
        Line(source, "// number means and StressCorpus for why this file is generated and committed rather than");
        Line(source, "// one or the other.");
        Line(source, "");
        Line(source, "import proto \"invoice.proto\";");
        Line(source, "");
    }

    private static void Receiver(StringBuilder source)
    {
        Line(source, "extend InvoiceItem {");
        Line(source, $"    fn {Shared}() -> int64 {{");
        Line(source, "        return quantity * unit_price_cents;");
        Line(source, "    }");

        for (var step = 0; step < Steps; step++)
        {
            Line(source, "");
            Step(source, step);
        }

        Line(source, "");
        Deep(source);
        Line(source, "}");
        Line(source, "");
    }

    /// <remarks>
    /// A guard, a loop, an assignment and three calls to <see cref="Shared"/>. Division is avoided
    /// throughout: it is the one arithmetic operation this language attaches a policy and a zero
    /// divisor to, and a corpus that has to be reasoned about to be sure it binds cleanly is a
    /// corpus that will one day be measuring an error path.
    /// </remarks>
    private static void Step(StringBuilder source, int step)
    {
        Line(source, $"    fn step_{step}(factor: int64) -> int64 {{");
        Line(source, $"        var carried: int64 = {Shared}();");
        Line(source, "        var taken: int64 = 0;");
        Line(source, "");
        Line(source, "        if factor <= 0 {");
        Line(source, "            return carried;");
        Line(source, "        }");
        Line(source, "");
        Line(source, "        while taken < factor {");
        Line(source, $"            carried = carried + {Shared}() * taken;");
        Line(source, "            taken = taken + 1;");
        Line(source, "        }");
        Line(source, "");
        Line(source, $"        return carried - {Shared}();");
        Line(source, "    }");
    }

    /// <remarks>
    /// One body whose scope is deep rather than wide. Every local reads the one before it, so none
    /// of them can be dropped as unused and a scope query at the end has all of them to gather.
    /// </remarks>
    private static void Deep(StringBuilder source)
    {
        Line(source, "    fn deep_locals() -> int64 {");
        Line(source, $"        var held_0: int64 = {Shared}();");

        for (var local = 1; local < Locals; local++)
        {
            Line(source, $"        var held_{local}: int64 = held_{local - 1} + {Shared}();");
        }

        Line(source, "");
        Line(source, $"        return held_{Locals - 1};");
        Line(source, "    }");
    }

    /// <remarks>
    /// A loop binding reaching methods through a receiver, which is the shape none of the bodies
    /// above has: every reference in them is to something the same declaration introduced.
    /// </remarks>
    private static void Aggregate(StringBuilder source)
    {
        Line(source, "extend Invoice {");
        Line(source, "    fn stepped_total_cents() -> int64 {");
        Line(source, "        var total: int64 = 0;");
        Line(source, "");
        Line(source, "        for item in items {");
        Line(source, $"            total = total + item.{Shared}();");
        Line(source, "            total = total + item.step_0(3);");
        Line(source, $"            total = total + item.step_{Steps - 1}(5);");
        Line(source, "            total = total + item.deep_locals();");
        Line(source, "        }");
        Line(source, "");
        Line(source, "        return total;");
        Line(source, "    }");
        Line(source, "}");
    }

    private static void Line(StringBuilder source, string text) => source.Append(text).Append('\n');
}
