using ProtoLang.Backend;

namespace ProtoLang.Backend.CSharp;

/// <summary>
/// The fixed C# support file emitted alongside generated tests.
/// </summary>
/// <remarks>
/// <para>
/// A ProtoLang <c>expect fail</c> test asserts that a method terminates the process, which is what
/// <c>on_zero fail</c> compiles to. That cannot be observed from inside the process it kills, so the
/// generated test relaunches the test assembly, asks it for one named test, and inspects what the
/// child did.
/// </para>
/// <para>
/// The verdict comes from what the child printed rather than from waiting for it to exit.
/// <c>Environment.FailFast</c> hands the process to the host's crash reporting, and on a developer
/// machine with a postmortem debugger registered under <c>AeDebug</c> -- which installing Visual
/// Studio does -- that blocks indefinitely waiting for a prompt no one will answer. A harness that
/// waited for the exit code would hang on exactly the machines this feature is written on.
/// </para>
/// <para>
/// Emitted as its own file so that compiling several ProtoLang sources into one assembly does not
/// produce duplicate definitions.
/// </para>
/// </remarks>
public static class CSharpTestRuntime
{
    public const string FileName = "ProtoLangTestSupport.g.cs";

    public const string NamespaceName = "ProtoLang.Runtime";

    public const string TypeName = "global::ProtoLang.Runtime.ProtoLangTestSupport";

    /// <summary>Environment variable naming the single test a child process should run.</summary>
    public const string TestVariable = "PROTOLANG_EXPECT_FAIL_TEST";

    /// <summary>Printed by the child immediately before it calls the method under test.</summary>
    public const string StartedMarker = "PROTOLANG-EXPECT-FAIL-STARTED ";

    /// <summary>Printed by the child if that call returns, which is the failure this test looks for.</summary>
    public const string ReturnedMarker = "PROTOLANG-EXPECT-FAIL-RETURNED ";

    /// <summary>Exit code a child uses when it does not recognize the requested test name.</summary>
    public const int UnknownTestExitCode = 92;

    /// <summary>
    /// Exit code a child uses after the body returned. The parent decides on the marker rather than
    /// this, but a child that ends silently should still say why.
    /// </summary>
    public const int DidNotTerminateExitCode = 91;

    /// <summary>How long to wait for evidence before giving up on the child.</summary>
    private const int GraceMilliseconds = 15000;

    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoLang C# test support file. Generated by protolangc.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        using (writer.Block($"namespace {NamespaceName}"))
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Runs a ProtoLang 'expect fail' test out of process, because the behavior it");
            writer.WriteLine("/// asserts is that the process does not survive the call.");
            writer.WriteLine("/// </summary>");
            using (writer.Block("internal static class ProtoLangTestSupport"))
            {
                EmitConstants(writer);
                writer.WriteLine();
                EmitRequestedTest(writer);
                writer.WriteLine();
                EmitDescribeExpectFail(writer);
                writer.WriteLine();
                EmitCreateChildStartInfo(writer);
                writer.WriteLine();
                EmitBufferHelpers(writer);
            }
        }

        return writer.ToString();
    }

    private static void EmitConstants(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>Names the single test a child process should run.</summary>");
        writer.WriteLine($"public const string TestVariable = \"{TestVariable}\";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>Printed by the child just before it calls the method under test.</summary>");
        writer.WriteLine($"public const string StartedMarker = \"{StartedMarker}\";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>Printed by the child if that call returns.</summary>");
        writer.WriteLine($"public const string ReturnedMarker = \"{ReturnedMarker}\";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>Start of the line the ProtoLang fail path writes to standard error.</summary>");
        writer.WriteLine($"public const string FailMarker = \"{CSharpRuntime.FailMarker}\";");
        writer.WriteLine();
        writer.WriteLine("/// <summary>Exit code used when the child does not recognize the requested test.</summary>");
        writer.WriteLine($"public const int UnknownTest = {UnknownTestExitCode};");
        writer.WriteLine();
        writer.WriteLine("/// <summary>Exit code used when the body returned instead of terminating.</summary>");
        writer.WriteLine($"public const int DidNotTerminate = {DidNotTerminateExitCode};");
        writer.WriteLine();
        writer.WriteLine("/// <summary>How long to wait for the child to prove what it did.</summary>");
        writer.WriteLine($"private const int GraceMilliseconds = {GraceMilliseconds};");
    }

    /// <summary>
    /// Emits the lookup each generated module initializer uses to decide whether the child process
    /// was asked for one of its own tests. Keys are prefixed with the source file name so several
    /// ProtoLang sources can compile into one assembly without their test names colliding.
    /// </summary>
    private static void EmitRequestedTest(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// The test this process was asked to run, if it belongs to");
        writer.WriteLine("/// <paramref name=\"sourceName\"/>. Null in a normal test run.");
        writer.WriteLine("/// </summary>");
        using (writer.Block("public static string? RequestedTest(string sourceName)"))
        {
            writer.WriteLine("var requested = global::System.Environment.GetEnvironmentVariable(TestVariable);");
            using (writer.Block("if (string.IsNullOrEmpty(requested))"))
            {
                writer.WriteLine("return null;");
            }

            writer.WriteLine();
            writer.WriteLine("var prefix = sourceName + \":\";");
            writer.WriteLine("return requested.StartsWith(prefix, global::System.StringComparison.Ordinal)");
            writer.Indent();
            writer.WriteLine("? requested.Substring(prefix.Length)");
            writer.WriteLine(": null;");
            writer.Unindent();
        }
    }

    private static void EmitDescribeExpectFail(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Runs one test in a child process. Returns null when the child terminated the way");
        writer.WriteLine("/// the test expects, and otherwise says what it did instead.");
        writer.WriteLine("/// </summary>");
        using (writer.Block("public static string? DescribeExpectFail(string testKey)"))
        {
            writer.WriteLine("// A child must never spawn a child: if the key ever failed to match a module");
            writer.WriteLine("// initializer, the child would fall through into the test run itself.");
            using (writer.Block(
                "if (!string.IsNullOrEmpty(global::System.Environment.GetEnvironmentVariable(TestVariable)))"))
            {
                writer.WriteLine("return \"the test was already running inside a child process\";");
            }

            writer.WriteLine();
            writer.WriteLine("using var process = global::System.Diagnostics.Process.Start(CreateChildStartInfo(testKey));");
            using (writer.Block("if (process is null)"))
            {
                writer.WriteLine("return \"the child process could not be started\";");
            }

            writer.WriteLine();
            writer.WriteLine("var buffer = new global::System.Text.StringBuilder();");
            writer.WriteLine("process.OutputDataReceived += (_, e) => Append(buffer, e.Data);");
            writer.WriteLine("process.ErrorDataReceived += (_, e) => Append(buffer, e.Data);");
            writer.WriteLine("process.BeginOutputReadLine();");
            writer.WriteLine("process.BeginErrorReadLine();");
            writer.WriteLine();
            writer.WriteLine("// Stop as soon as the child has said enough, rather than waiting for it to");
            writer.WriteLine("// exit: a fail-fast can leave the process parked in the host's crash reporting.");
            writer.WriteLine("var deadline = global::System.Environment.TickCount64 + GraceMilliseconds;");
            writer.WriteLine("var exited = false;");
            writer.WriteLine();
            using (writer.Block("while (true)"))
            {
                writer.WriteLine("exited = process.WaitForExit(200);");
                using (writer.Block("if (exited)"))
                {
                    writer.WriteLine("break;");
                }

                writer.WriteLine();
                writer.WriteLine("var progress = Snapshot(buffer);");
                using (writer.Block(
                    "if (progress.Contains(FailMarker, global::System.StringComparison.Ordinal)"
                    + " || progress.Contains(ReturnedMarker, global::System.StringComparison.Ordinal))"))
                {
                    writer.WriteLine("break;");
                }

                writer.WriteLine();
                using (writer.Block("if (global::System.Environment.TickCount64 > deadline)"))
                {
                    writer.WriteLine("break;");
                }
            }

            writer.WriteLine();
            using (writer.Block("if (!exited)"))
            {
                using (writer.Block("try"))
                {
                    writer.WriteLine("process.Kill(entireProcessTree: true);");
                }

                using (writer.Block("catch (global::System.InvalidOperationException)"))
                {
                    writer.WriteLine("// Already gone.");
                }
            }

            writer.WriteLine();
            writer.WriteLine("var output = Snapshot(buffer);");
            writer.WriteLine();
            writer.WriteLine("// However the child ended says nothing unless it actually reached the body:");
            writer.WriteLine("// a child that fell through to an ordinary test run would also end non-zero.");
            using (writer.Block(
                "if (!output.Contains(StartedMarker + testKey, global::System.StringComparison.Ordinal))"))
            {
                writer.WriteLine("return \"the child process never reached the method under test\";");
            }

            writer.WriteLine();
            using (writer.Block(
                "if (output.Contains(ReturnedMarker + testKey, global::System.StringComparison.Ordinal))"))
            {
                writer.WriteLine("return \"the method returned instead of terminating the process\";");
            }

            writer.WriteLine();
            using (writer.Block("if (exited)"))
            {
                writer.WriteLine("return process.ExitCode == 0 ? \"the child process exited normally\" : null;");
            }

            writer.WriteLine();
            writer.WriteLine("// Still running. The ProtoLang fail path writes its diagnostic before handing");
            writer.WriteLine("// the process to the host, so that line is the proof, not the exit code.");
            writer.WriteLine("return output.Contains(FailMarker, global::System.StringComparison.Ordinal)");
            writer.Indent();
            writer.WriteLine("? null");
            writer.WriteLine(": \"the child process neither terminated nor reported a ProtoLang failure\";");
            writer.Unindent();
        }
    }

    private static void EmitCreateChildStartInfo(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>Relaunches this test assembly, asking it for one test.</summary>");
        using (writer.Block(
            "private static global::System.Diagnostics.ProcessStartInfo CreateChildStartInfo(string testKey)"))
        {
            writer.WriteLine("var baseDirectory = global::System.AppContext.BaseDirectory;");
            writer.WriteLine("var stem = typeof(ProtoLangTestSupport).Assembly.GetName().Name ?? \"tests\";");
            writer.WriteLine();
            using (writer.Block("var startInfo = new global::System.Diagnostics.ProcessStartInfo", "};"))
            {
                writer.WriteLine("RedirectStandardOutput = true,");
                writer.WriteLine("RedirectStandardError = true,");
                writer.WriteLine("UseShellExecute = false,");
                writer.WriteLine("WorkingDirectory = baseDirectory,");
            }

            writer.WriteLine();
            writer.WriteLine("// Prefer the apphost beside the assembly; fall back to the shared host.");
            writer.WriteLine("var apphost = global::System.IO.Path.Combine(");
            writer.Indent();
            writer.WriteLine("baseDirectory,");
            writer.WriteLine("stem + (global::System.OperatingSystem.IsWindows() ? \".exe\" : string.Empty));");
            writer.Unindent();
            writer.WriteLine();
            using (writer.Block("if (global::System.IO.File.Exists(apphost))"))
            {
                writer.WriteLine("startInfo.FileName = apphost;");
            }

            using (writer.Block("else"))
            {
                writer.WriteLine("startInfo.FileName =");
                writer.Indent();
                writer.WriteLine(
                    "global::System.Environment.GetEnvironmentVariable(\"DOTNET_HOST_PATH\") ?? \"dotnet\";");
                writer.Unindent();
                writer.WriteLine("startInfo.ArgumentList.Add(\"exec\");");
                writer.WriteLine("startInfo.ArgumentList.Add(");
                writer.Indent();
                writer.WriteLine("global::System.IO.Path.Combine(baseDirectory, stem + \".dll\"));");
                writer.Unindent();
            }

            writer.WriteLine();
            writer.WriteLine("startInfo.Environment[TestVariable] = testKey;");
            writer.WriteLine();
            writer.WriteLine("// The child is expected to die. Do not spend time collecting a dump for it.");
            writer.WriteLine("startInfo.Environment[\"DOTNET_DbgEnableMiniDump\"] = \"0\";");
            writer.WriteLine();
            writer.WriteLine("return startInfo;");
        }
    }

    private static void EmitBufferHelpers(SourceWriter writer)
    {
        writer.WriteLine("// Both pipes feed one buffer, so the order the child printed things in survives.");
        using (writer.Block("private static void Append(global::System.Text.StringBuilder buffer, string? line)"))
        {
            using (writer.Block("if (line is null)"))
            {
                writer.WriteLine("return;");
            }

            writer.WriteLine();
            using (writer.Block("lock (buffer)"))
            {
                writer.WriteLine("buffer.AppendLine(line);");
            }
        }

        writer.WriteLine();
        using (writer.Block("private static string Snapshot(global::System.Text.StringBuilder buffer)"))
        {
            using (writer.Block("lock (buffer)"))
            {
                writer.WriteLine("return buffer.ToString();");
            }
        }
    }
}
