using ProtoLang.Backend;

namespace ProtoLang.Backend.CSharp;

/// <summary>
/// The fixed C# support file emitted alongside generated code.
/// </summary>
/// <remarks>
/// <para>
/// Addition, subtraction, multiplication, and negation wrap correctly inside <c>unchecked(...)</c>,
/// so those need no helper. Division does not: <c>long.MinValue / -1</c> raises
/// <see cref="OverflowException"/> on x86/x64 from the hardware divide instruction itself, and
/// <c>unchecked</c> has no effect on it. The same applies to <c>%</c>.
/// </para>
/// <para>
/// Emitted as its own file so that compiling several ProtoLang sources into one assembly does not
/// produce duplicate definitions.
/// </para>
/// </remarks>
public static class CSharpRuntime
{
    public const string FileName = "ProtoLangArithmetic.g.cs";

    public const string NamespaceName = "ProtoLang.Runtime";

    public const string TypeName = "global::ProtoLang.Runtime.ProtoLangArithmetic";

    // Lazy rather than a field initializer: Build() reads static tables declared further down,
    // and static field initializers run in declaration order.
    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoLang C# support file. Generated by protolangc.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        using (writer.Block($"namespace {NamespaceName}"))
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Numeric operations whose ProtoLang semantics C#'s <c>unchecked</c> does not");
            writer.WriteLine("/// already provide: division, which traps on MIN / -1 regardless of context, and");
            writer.WriteLine("/// conversion from floating point to an integer, which the language leaves");
            writer.WriteLine("/// unspecified when the value is out of range.");
            writer.WriteLine("/// </summary>");
            using (writer.Block("internal static class ProtoLangArithmetic"))
            {
                EmitFail(writer);
                writer.WriteLine();

                var first = true;
                foreach (var (type, isSigned) in IntegerTypes)
                {
                    if (!first)
                    {
                        writer.WriteLine();
                    }

                    first = false;
                    EmitDivide(writer, type, isSigned);
                    writer.WriteLine();
                    EmitModulo(writer, type, isSigned);
                    writer.WriteLine();
                    EmitDivideOr(writer, type, isSigned);
                    writer.WriteLine();
                    EmitModuloOr(writer, type, isSigned);
                    writer.WriteLine();
                    EmitDivideOrFail(writer, type);
                    writer.WriteLine();
                    EmitModuloOrFail(writer, type);
                }

                foreach (var target in FloatToIntegerTargets)
                {
                    writer.WriteLine();
                    EmitFloatToInteger(writer, target);
                }
            }
        }

        return writer.ToString();
    }

    private static readonly (string Type, bool IsSigned)[] IntegerTypes =
    [
        ("int", true),
        ("long", true),
        ("uint", false),
        ("ulong", false),
    ];

    /// <summary>
    /// Floating-point to integer conversion targets: the C# type, the helper name, and the two
    /// range guards.
    /// </summary>
    /// <remarks>
    /// The guards are not uniform, because the bound is not always representable as a
    /// <c>double</c>. For the 32-bit types both bounds are exact, so a strict comparison is right:
    /// a value just past <c>int.MaxValue</c> truncates to <c>int.MaxValue</c> anyway. For the
    /// 64-bit types the positive bound is not exact -- the nearest <c>double</c> above
    /// <c>long.MaxValue</c> is 2^63 -- so the guard has to be inclusive against that power of two
    /// or the conversion would be handed a value it cannot represent.
    /// </remarks>
    private static readonly (string Type, string Method, string Low, string High)[] FloatToIntegerTargets =
    [
        ("int", "ToInt32", "value < int.MinValue", "value > int.MaxValue"),
        ("long", "ToInt64", "value < -9223372036854775808.0", "value >= 9223372036854775808.0"),
        ("uint", "ToUInt32", "value <= 0.0", "value > uint.MaxValue"),
        ("ulong", "ToUInt64", "value <= 0.0", "value >= 18446744073709551616.0"),
    ];

    /// <summary>
    /// Emits a saturating, truncating conversion from <c>double</c> to one integer type.
    /// </summary>
    /// <remarks>
    /// C# leaves an out-of-range floating-point to integer conversion unspecified in an unchecked
    /// context and throws in a checked one, so neither default is usable: the first is not a
    /// portable semantic and the second is a property of the consumer's build. Writing the clamp
    /// out makes the result the same in every target and under every compiler flag.
    /// </remarks>
    private static void EmitFloatToInteger(SourceWriter writer, (string Type, string Method, string Low, string High) target)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine($"/// Converts to <c>{target.Type}</c>, truncating toward zero and clamping to the");
        writer.WriteLine("/// type's bounds. NaN converts to zero.");
        writer.WriteLine("/// </summary>");
        using (writer.Block($"public static {target.Type} {target.Method}(double value)"))
        {
            using (writer.Block("if (double.IsNaN(value))"))
            {
                writer.WriteLine("return 0;");
            }

            writer.WriteLine();
            using (writer.Block($"if ({target.Low})"))
            {
                writer.WriteLine($"return {target.Type}.MinValue;");
            }

            writer.WriteLine();
            using (writer.Block($"if ({target.High})"))
            {
                writer.WriteLine($"return {target.Type}.MaxValue;");
            }

            writer.WriteLine();
            writer.WriteLine($"return unchecked(({target.Type})value);");
        }
    }

    /// <summary>
    /// Prefix of the line the fail path writes to standard error.
    /// </summary>
    public const string FailMarker = "ProtoLang: ";

    /// <summary>
    /// Exit code of a program stopped by <c>on_zero fail</c>. <c>EX_SOFTWARE</c> from
    /// <c>sysexits.h</c>, and normative: every backend reports the same code (spec 10.2.1).
    /// </summary>
    public const int FailExitCode = 70;

    /// <summary>
    /// Emits the deterministic-termination helper behind <c>on_zero fail</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Termination rather than an exception, because a catchable exception would let a consumer
    /// resume from a state the author said has no valid result, and because it would not mean the
    /// same thing in every target.
    /// </para>
    /// <para>
    /// <see cref="Environment.Exit(int)"/> rather than <see cref="Environment.FailFast(string?)"/>:
    /// fail-fast is a crash-reporting primitive, so it hands the process to Windows Error Reporting
    /// and to any postmortem debugger registered under <c>AeDebug</c> -- which installing Visual
    /// Studio does. Generated library code must not be able to put a dialog on someone's screen. It
    /// also leaves the exit code up to the host, where this reports <see cref="FailExitCode"/> in
    /// every backend. Nothing can cancel an Exit, so it is no more recoverable than a fail-fast.
    /// </para>
    /// <para>
    /// The diagnostic is written to standard error first, so the reason survives however the host
    /// reports the exit. The C++ runtime writes the same line for the same reason.
    /// </para>
    /// </remarks>
    private static void EmitFail(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Terminates the process. Reached only from an 'on_zero fail' clause, where the");
        writer.WriteLine("/// author declared that no substitute value is correct.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        using (writer.Block("private static void Fail(string operation)"))
        {
            writer.WriteLine("// The one place generated code performs I/O. Spec 20 bans I/O in method");
            writer.WriteLine("// bodies; this is a fatal-error path rather than behavior, and the reason has");
            writer.WriteLine("// to survive however the host reports the exit.");
            writer.WriteLine($"global::System.Console.Error.WriteLine(\"{FailMarker}\" + operation + \" by zero\");");
            writer.WriteLine("global::System.Console.Error.Flush();");
            writer.WriteLine();
            writer.WriteLine("// Exit, not FailFast: a fail-fast is a crash report, and generated library");
            writer.WriteLine("// code must not be able to raise a dialog or invoke a postmortem debugger.");
            writer.WriteLine($"global::System.Environment.Exit({FailExitCode});");
        }
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback. The fallback is
    /// evaluated eagerly at the call site; ProtoLang expressions have no side effects, so this is
    /// indistinguishable from lazy evaluation and keeps the emitted code a single expression.
    /// </summary>
    private static void EmitDivideOr(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Division that yields <paramref name=\"onZero\"/> instead of failing.</summary>");
        using (writer.Block($"public static {type} WrapDivideOr({type} left, {type} right, {type} onZero)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("return onZero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return WrapDivide(left, right);");
        }
    }

    private static void EmitModuloOr(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Remainder that yields <paramref name=\"onZero\"/> instead of failing.</summary>");
        using (writer.Block($"public static {type} WrapModuloOr({type} left, {type} right, {type} onZero)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("return onZero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return WrapModulo(left, right);");
        }
    }

    private static void EmitDivideOrFail(SourceWriter writer, string type)
    {
        writer.WriteLine("/// <summary>Division that terminates the process on a zero divisor.</summary>");
        using (writer.Block($"public static {type} WrapDivideOrFail({type} left, {type} right)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("Fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine("return WrapDivide(left, right);");
        }
    }

    private static void EmitModuloOrFail(SourceWriter writer, string type)
    {
        writer.WriteLine("/// <summary>Remainder that terminates the process on a zero divisor.</summary>");
        using (writer.Block($"public static {type} WrapModuloOrFail({type} left, {type} right)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("Fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine("return WrapModulo(left, right);");
        }
    }

    private static void EmitDivide(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Division with wrapping overflow. Division by zero still throws.</summary>");
        using (writer.Block($"public static {type} WrapDivide({type} left, {type} right)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN / -1 overflows and traps even in an unchecked context.");
                writer.WriteLine("// The wrapped result is MIN itself.");
                using (writer.Block("if (right == -1)"))
                {
                    writer.WriteLine("return unchecked(0 - left);");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return left / right;");
        }
    }

    private static void EmitModulo(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Remainder with wrapping overflow. Modulo by zero still throws.</summary>");
        using (writer.Block($"public static {type} WrapModulo({type} left, {type} right)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN % -1 traps for the same reason; the wrapped result is 0.");
                using (writer.Block("if (right == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return left % right;");
        }
    }
}
