using System.Text;
using ProtoLang.Backend;

namespace ProtoLang.Backend.CSharp;

/// <summary>
/// The MSBuild project that builds and runs generated C# ProtoLang tests.
/// </summary>
/// <remarks>
/// <para>
/// This exists because <c>--test-out</c> on its own produces source that nothing can build. The
/// repository's own harness knows the answer, but as <c>internal</c> code in the test assembly, so
/// every consumer was left to rediscover it from prose.
/// </para>
/// <para>
/// It is deliberately not a copy of that harness project. <c>CSharpTestWorkspace</c> is tuned for a
/// hostile offline sandbox -- it clears every NuGet source, treats warnings as errors, forces
/// checked arithmetic, and stubs out <c>Directory.Build.props</c> so nothing above it applies. Each
/// of those is right for proving the compiler's output survives a hostile project and wrong for a
/// project a user drops into their own repository, so none of them are emitted here.
/// </para>
/// </remarks>
public static class CSharpTestProject
{
    public const string FileName = "ProtoLangTests.csproj";

    /// <summary>
    /// Package versions the emitted project pins.
    /// </summary>
    /// <remarks>
    /// A consumer has no <c>Directory.Packages.props</c> of ours, so unlike the harness project
    /// these cannot be left to central package management and must be stated. That makes them a
    /// second copy of versions this repository already declares, so
    /// <c>ScaffoldTests.EveryPinnedVersionMatchesCentralPackageManagement</c> fails if the two ever
    /// disagree.
    /// </remarks>
    public static IReadOnlyDictionary<string, string> PackageVersions { get; } =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Google.Protobuf"] = "3.31.1",
            ["Grpc.Tools"] = "2.80.0",
            ["Microsoft.NET.Test.Sdk"] = "17.14.1",
            ["xunit.v3"] = "3.2.2",
            ["xunit.runner.visualstudio"] = "3.1.5",
        };

    public static string Build(ScaffoldOptions options)
    {
        var builder = new StringBuilder();

        builder.AppendLine("<!--");
        builder.AppendLine("    Generated by protolangc. Builds and runs ProtoLang tests for this project's");
        builder.AppendLine("    generated C# behavior. Changes to this file will be lost when it is regenerated.");
        builder.AppendLine("-->");
        builder.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        builder.AppendLine();
        builder.AppendLine("  <PropertyGroup>");
        builder.AppendLine("    <TargetFramework>net10.0</TargetFramework>");
        builder.AppendLine("    <Nullable>enable</Nullable>");
        builder.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");
        builder.AppendLine("    <IsPackable>false</IsPackable>");
        builder.AppendLine("    <!--");
        builder.AppendLine("      A ProtoLang 'expect fail' test asserts that a method terminates the process, which");
        builder.AppendLine("      cannot be observed from inside it. The generated test relaunches this assembly for");
        builder.AppendLine("      one named test and inspects how the child ended, so it has to be executable.");
        builder.AppendLine("    -->");
        builder.AppendLine("    <OutputType>Exe</OutputType>");
        builder.AppendLine("    <!--");
        builder.AppendLine("      The package references below state their own versions, which is an error when a");
        builder.AppendLine("      Directory.Packages.props anywhere above this directory turns central package");
        builder.AppendLine("      management on (NU1008). This project is self-contained, so opt it back out.");
        builder.AppendLine("    -->");
        builder.AppendLine("    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>");
        builder.AppendLine("  </PropertyGroup>");
        builder.AppendLine();
        builder.AppendLine("  <ItemGroup>");

        foreach (var (package, version) in PackageVersions)
        {
            // Grpc.Tools contributes build-time protoc integration and nothing at runtime, so it
            // must not flow to anything referencing this project.
            var attributes = package == "Grpc.Tools"
                ? " PrivateAssets=\"all\" ExcludeAssets=\"runtime\""
                : string.Empty;

            builder.AppendLine(
                $"    <PackageReference Include=\"{package}\" Version=\"{version}\"{attributes} />");
        }

        builder.AppendLine("  </ItemGroup>");
        builder.AppendLine();
        builder.AppendLine("  <!--");
        // No '--' anywhere in an emitted comment: XML forbids it, so naming the compiler flag
        // literally here would produce a project MSBuild refuses to load (MSB4025).
        builder.AppendLine("    The behavior emitted into the compiler's output directory. The generated tests");
        builder.AppendLine("    call into it, so it is compiled here rather than referenced as a separate project.");
        builder.AppendLine("  -->");
        builder.AppendLine("  <ItemGroup>");
        builder.AppendLine(
            $"    <Compile Include=\"{Escape(Join(options.BehaviorDirectory, "**/*.cs"))}\" />");
        builder.AppendLine("  </ItemGroup>");
        builder.AppendLine();
        builder.AppendLine("  <!--");
        builder.AppendLine("    Protobuf message classes. Grpc.Tools runs protoc during the build, so there is no");
        builder.AppendLine("    separate protoc step to remember and no generated .cs to keep in sync by hand.");
        builder.AppendLine("  -->");
        builder.AppendLine("  <ItemGroup>");

        foreach (var proto in options.ProtoFiles)
        {
            var include = Escape(Join(proto.ProtoRoot, proto.RelativePath));
            var root = Escape(Normalize(proto.ProtoRoot));
            builder.AppendLine(
                $"    <Protobuf Include=\"{include}\" ProtoRoot=\"{root}\" GrpcServices=\"None\" />");
        }

        builder.AppendLine("  </ItemGroup>");
        builder.AppendLine();
        builder.AppendLine("</Project>");

        return builder.ToString();
    }

    /// <summary>
    /// MSBuild accepts either separator on Windows and only this one elsewhere, so emitted paths use
    /// it regardless of the platform the compiler happened to run on.
    /// </summary>
    private static string Normalize(string path) => path.Replace('\\', '/');

    private static string Join(string directory, string relative)
    {
        var normalized = Normalize(directory);
        return normalized.Length == 0 || normalized == "."
            ? relative
            : normalized.TrimEnd('/') + "/" + relative;
    }

    /// <summary>Escapes the five XML predefined entities, so a path with an ampersand still parses.</summary>
    private static string Escape(string value) => value
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\"", "&quot;")
        .Replace("'", "&apos;");
}
