using ProtoLang.Backend;

namespace ProtoLang.Backend.CSharp;

/// <summary>
/// The fixed C# support file emitted alongside generated code.
/// </summary>
/// <remarks>
/// <para>
/// Addition, subtraction, multiplication, and negation wrap correctly inside <c>unchecked(...)</c>,
/// so those need no helper. Division does not: <c>long.MinValue / -1</c> raises
/// <see cref="OverflowException"/> on x86/x64 from the hardware divide instruction itself, and
/// <c>unchecked</c> has no effect on it. The same applies to <c>%</c>.
/// </para>
/// <para>
/// Emitted as its own file so that compiling several ProtoLang sources into one assembly does not
/// produce duplicate definitions.
/// </para>
/// </remarks>
public static class CSharpRuntime
{
    public const string FileName = "ProtoLangArithmetic.g.cs";

    public const string NamespaceName = "ProtoLang.Runtime";

    public const string TypeName = "global::ProtoLang.Runtime.ProtoLangArithmetic";

    // Lazy rather than a field initializer: Build() reads static tables declared further down,
    // and static field initializers run in declaration order.
    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter();

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoLang C# support file. Generated by protolangc.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#nullable enable");
        writer.WriteLine();

        using (writer.Block($"namespace {NamespaceName}"))
        {
            writer.WriteLine("/// <summary>");
            writer.WriteLine("/// Integer operations whose ProtoLang wrapping semantics C#'s <c>unchecked</c>");
            writer.WriteLine("/// does not already provide.");
            writer.WriteLine("/// </summary>");
            using (writer.Block("internal static class ProtoLangArithmetic"))
            {
                EmitFail(writer);
                writer.WriteLine();

                var first = true;
                foreach (var (type, isSigned) in IntegerTypes)
                {
                    if (!first)
                    {
                        writer.WriteLine();
                    }

                    first = false;
                    EmitDivide(writer, type, isSigned);
                    writer.WriteLine();
                    EmitModulo(writer, type, isSigned);
                    writer.WriteLine();
                    EmitDivideOr(writer, type, isSigned);
                    writer.WriteLine();
                    EmitModuloOr(writer, type, isSigned);
                    writer.WriteLine();
                    EmitDivideOrFail(writer, type);
                    writer.WriteLine();
                    EmitModuloOrFail(writer, type);
                }
            }
        }

        return writer.ToString();
    }

    private static readonly (string Type, bool IsSigned)[] IntegerTypes =
    [
        ("int", true),
        ("long", true),
        ("uint", false),
        ("ulong", false),
    ];

    /// <summary>
    /// Prefix of the line the fail path writes to standard error. Also the marker a test harness
    /// uses as proof that control reached a terminal failure.
    /// </summary>
    public const string FailMarker = "ProtoLang: ";

    /// <summary>
    /// Emits the deterministic-termination helper behind <c>on_zero fail</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="Environment.FailFast(string?)"/> rather than an exception, because a catchable
    /// exception would let a consumer resume from a state the author said has no valid result, and
    /// because C++ has no equivalent of a catchable exception under this design.
    /// </para>
    /// <para>
    /// The diagnostic is written to standard error before that call rather than left to FailFast's
    /// own reporting, which varies by host: on a machine with a postmortem debugger registered, the
    /// process can block indefinitely before printing anything. The C++ runtime writes the same
    /// line for the same reason.
    /// </para>
    /// </remarks>
    private static void EmitFail(SourceWriter writer)
    {
        writer.WriteLine("/// <summary>");
        writer.WriteLine("/// Terminates the process. Reached only from an 'on_zero fail' clause, where the");
        writer.WriteLine("/// author declared that no substitute value is correct.");
        writer.WriteLine("/// </summary>");
        writer.WriteLine("[global::System.Diagnostics.CodeAnalysis.DoesNotReturn]");
        using (writer.Block("private static void Fail(string operation)"))
        {
            writer.WriteLine($"var message = \"{FailMarker}\" + operation + \" by zero\";");
            writer.WriteLine();
            writer.WriteLine("// The one place generated code performs I/O. Spec 20 bans I/O in method");
            writer.WriteLine("// bodies; this is a fatal-error path rather than behavior, and how a host");
            writer.WriteLine("// reports a fail-fast is not something a portable diagnostic can rely on.");
            writer.WriteLine("global::System.Console.Error.WriteLine(message);");
            writer.WriteLine("global::System.Console.Error.Flush();");
            writer.WriteLine();
            writer.WriteLine("global::System.Environment.FailFast(message);");
        }
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback. The fallback is
    /// evaluated eagerly at the call site; ProtoLang expressions have no side effects, so this is
    /// indistinguishable from lazy evaluation and keeps the emitted code a single expression.
    /// </summary>
    private static void EmitDivideOr(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Division that yields <paramref name=\"onZero\"/> instead of failing.</summary>");
        using (writer.Block($"public static {type} WrapDivideOr({type} left, {type} right, {type} onZero)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("return onZero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return WrapDivide(left, right);");
        }
    }

    private static void EmitModuloOr(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Remainder that yields <paramref name=\"onZero\"/> instead of failing.</summary>");
        using (writer.Block($"public static {type} WrapModuloOr({type} left, {type} right, {type} onZero)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("return onZero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return WrapModulo(left, right);");
        }
    }

    private static void EmitDivideOrFail(SourceWriter writer, string type)
    {
        writer.WriteLine("/// <summary>Division that terminates the process on a zero divisor.</summary>");
        using (writer.Block($"public static {type} WrapDivideOrFail({type} left, {type} right)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("Fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine("return WrapDivide(left, right);");
        }
    }

    private static void EmitModuloOrFail(SourceWriter writer, string type)
    {
        writer.WriteLine("/// <summary>Remainder that terminates the process on a zero divisor.</summary>");
        using (writer.Block($"public static {type} WrapModuloOrFail({type} left, {type} right)"))
        {
            using (writer.Block("if (right == 0)"))
            {
                writer.WriteLine("Fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine("return WrapModulo(left, right);");
        }
    }

    private static void EmitDivide(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Division with wrapping overflow. Division by zero still throws.</summary>");
        using (writer.Block($"public static {type} WrapDivide({type} left, {type} right)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN / -1 overflows and traps even in an unchecked context.");
                writer.WriteLine("// The wrapped result is MIN itself.");
                using (writer.Block("if (right == -1)"))
                {
                    writer.WriteLine("return unchecked(0 - left);");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return left / right;");
        }
    }

    private static void EmitModulo(SourceWriter writer, string type, bool isSigned)
    {
        writer.WriteLine("/// <summary>Remainder with wrapping overflow. Modulo by zero still throws.</summary>");
        using (writer.Block($"public static {type} WrapModulo({type} left, {type} right)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN % -1 traps for the same reason; the wrapped result is 0.");
                using (writer.Block("if (right == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return left % right;");
        }
    }
}
