namespace ProtoLang.Syntax;

public enum TokenKind
{
    EndOfFile,
    Unknown,

    Identifier,
    IntegerLiteral,
    FloatLiteral,
    StringLiteral,

    // Keywords. Spec 6.4 lists a candidate reserved set; `import`, `proto`, `double`,
    // `float`, and `bytes` are absent from that list but already used elsewhere in the
    // spec, so they are reserved here too.
    And,
    As,
    Bool,
    Break,
    Bytes,
    Case,
    Continue,
    Double,
    Else,
    Enum,
    Extend,
    Fail,
    False,
    Float,
    Fn,
    For,
    If,
    Import,
    In,
    Int32,
    Int64,
    Message,
    Not,
    OnZero,
    Or,
    Proto,
    Arg,
    Expect,
    Receiver,
    Return,
    String,
    Switch,
    Test,
    True,
    UInt32,
    UInt64,
    Var,
    Virtual,
    Void,
    While,

    // Punctuation and operators.
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    Semicolon,
    Comma,
    Colon,
    Dot,
    Arrow,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Equals,
    EqualsEquals,
    BangEquals,
    Bang,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    AmpersandAmpersand,
    PipePipe,
}
