using ProtoLang.Backend;
using ProtoLang.Ir;

namespace ProtoLang.Backend.Cpp;

/// <summary>
/// The fixed C++ support header emitted alongside generated code.
/// </summary>
/// <remarks>
/// <para>
/// Signed integer overflow is undefined behavior in C++, not wraparound. Compilers exploit that:
/// an optimizer is entitled to assume it never happens and delete the code that would follow.
/// ProtoLang's wrapping semantics therefore cannot be expressed as bare <c>a + b</c>; every
/// operation routes through these helpers, which perform the arithmetic in the unsigned domain
/// where modular behavior is well-defined.
/// </para>
/// <para>
/// All three overflow policies are emitted whichever one the project selected. The header is
/// therefore identical for every compilation, which is what lets sources built under different
/// policies share one translation unit, and every helper is <c>inline</c> so the linker discards
/// what nothing calls.
/// </para>
/// <para>
/// Overflow is detected by hand rather than through <c>__builtin_add_overflow</c>, which MSVC does
/// not provide. The predicates below are the portable forms, factored out so that the three policy
/// wrappers agree with each other by construction rather than by three separate proofs.
/// </para>
/// </remarks>
public static class CppRuntime
{
    public const string FileName = "protolang_runtime.h";

    // Lazy rather than a field initializer: Build() reads static tables declared further down,
    // and static field initializers run in declaration order.
    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter("  ");

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoLang C++ support header. Generated by protolangc.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#ifndef PROTOLANG_RUNTIME_H_");
        writer.WriteLine("#define PROTOLANG_RUNTIME_H_");
        writer.WriteLine();
        writer.WriteLine("#include <cstdint>");
        writer.WriteLine("#include <cstdio>");
        writer.WriteLine("#include <cstdlib>");
        writer.WriteLine("#include <limits>");
        writer.WriteLine();
        writer.WriteLine("// Requires C++20: the conversion from an unsigned type back to the corresponding");
        writer.WriteLine("// signed type is defined as two's complement (P0907R4). Earlier standards leave that");
        writer.WriteLine("// conversion implementation-defined.");
        writer.WriteLine("static_assert(__cplusplus >= 202002L, \"ProtoLang generated code requires C++20 or later.\");");
        writer.WriteLine();

        using (writer.Block("namespace protolang_runtime"))
        {
            EmitFailHelper(writer);
            EmitFailOverflowHelper(writer);

            foreach (var (signed, unsigned, suffix) in IntegerTypes)
            {
                writer.WriteLine($"// --- {signed} ---");
                writer.WriteLine();

                EmitOverflowPredicates(writer, signed, unsigned, suffix);

                foreach (var behavior in Behaviors)
                {
                    EmitBinaryHelper(writer, behavior, "add", "+", "addition", signed, unsigned, suffix);
                    EmitBinaryHelper(writer, behavior, "sub", "-", "subtraction", signed, unsigned, suffix);
                    EmitBinaryHelper(writer, behavior, "mul", "*", "multiplication", signed, unsigned, suffix);
                    EmitNegateHelper(writer, behavior, signed, unsigned, suffix);
                    EmitDivideHelper(writer, behavior, signed, unsigned, suffix);
                    EmitModuloHelper(writer, behavior, signed, suffix);
                    EmitDivideOrHelper(writer, behavior, signed, suffix);
                    EmitModuloOrHelper(writer, behavior, signed, suffix);
                    EmitDivideOrFailHelper(writer, behavior, signed, suffix);
                    EmitModuloOrFailHelper(writer, behavior, signed, suffix);
                }
            }

            writer.WriteLine("// --- explicit conversions (10.3) ---");
            writer.WriteLine();

            foreach (var (type, suffix, low, high) in FloatToIntegerTargets)
            {
                EmitFloatToIntegerHelper(writer, type, suffix, low, high);
            }

            EmitNarrowToFloatHelper(writer);
        }

        writer.WriteLine();
        writer.WriteLine("#endif  // PROTOLANG_RUNTIME_H_");

        return writer.ToString();
    }

    /// <summary>(signed C++ type, unsigned C++ type, ProtoLang helper suffix).</summary>
    private static readonly (string Signed, string Unsigned, string Suffix)[] IntegerTypes =
    [
        ("::std::int32_t", "::std::uint32_t", "i32"),
        ("::std::int64_t", "::std::uint64_t", "i64"),
        ("::std::uint32_t", "::std::uint32_t", "u32"),
        ("::std::uint64_t", "::std::uint64_t", "u64"),
    ];

    /// <summary>
    /// Floating-point to integer conversion targets: the C++ type, the ProtoLang helper suffix,
    /// and the two range guards.
    /// </summary>
    /// <remarks>
    /// The guards are not uniform, because the bound is not always representable as a
    /// <c>double</c>. Both 32-bit bounds are exact, so a strict comparison is right: a value just
    /// past the maximum truncates to the maximum anyway. The positive 64-bit bounds are not exact
    /// -- the nearest <c>double</c> above <c>int64_t</c>'s maximum is 2^63 -- so those guards are
    /// inclusive against the power of two instead.
    /// </remarks>
    private static readonly (string Type, string Suffix, string Low, string High)[] FloatToIntegerTargets =
    [
        ("::std::int32_t", "i32", "v < -2147483648.0", "v > 2147483647.0"),
        ("::std::int64_t", "i64", "v < -9223372036854775808.0", "v >= 9223372036854775808.0"),
        ("::std::uint32_t", "u32", "v <= 0.0", "v > 4294967295.0"),
        ("::std::uint64_t", "u64", "v <= 0.0", "v >= 18446744073709551616.0"),
    ];

    /// <summary>
    /// Emits a saturating, truncating conversion from <c>double</c> to one integer type.
    /// </summary>
    /// <remarks>
    /// A floating-point value outside the destination integer's range is undefined behavior in
    /// C++, not a wrapped or clamped result, so the bounds are checked before the conversion
    /// rather than relying on what the hardware happens to do.
    /// </remarks>
    private static void EmitFloatToIntegerHelper(
        SourceWriter writer,
        string type,
        string suffix,
        string low,
        string high)
    {
        writer.WriteLine("// Truncates toward zero, clamping to the type's bounds. NaN converts to zero.");
        using (writer.Block($"inline {type} trunc_sat_f64_to_{suffix}(double v)"))
        {
            using (writer.Block("if (v != v)"))
            {
                writer.WriteLine("return 0;");
            }

            writer.WriteLine();
            using (writer.Block($"if ({low})"))
            {
                writer.WriteLine($"return ::std::numeric_limits<{type}>::min();");
            }

            writer.WriteLine();
            using (writer.Block($"if ({high})"))
            {
                writer.WriteLine($"return ::std::numeric_limits<{type}>::max();");
            }

            writer.WriteLine();
            writer.WriteLine($"return static_cast<{type}>(v);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the narrowing conversion from <c>double</c> to <c>float</c>.
    /// </summary>
    /// <remarks>
    /// A <c>double</c> outside <c>float</c>'s range is undefined behavior in C++, where the
    /// baseline result is an infinity. The threshold is not <c>FLT_MAX</c>: under round-to-nearest
    /// a <c>double</c> between <c>FLT_MAX</c> and 2^128 - 2^103 rounds down to <c>FLT_MAX</c>
    /// rather than overflowing, so guarding at <c>FLT_MAX</c> would produce an infinity where
    /// every other target produces a finite value.
    /// </remarks>
    private static void EmitNarrowToFloatHelper(SourceWriter writer)
    {
        writer.WriteLine("// Narrows to float. Out of range yields an infinity rather than undefined behavior.");
        using (writer.Block("inline float narrow_f64_to_f32(double v)"))
        {
            writer.WriteLine("// 2^128 - 2^103: the smallest magnitude that rounds to infinity, not FLT_MAX.");
            writer.WriteLine("// Spelled as a hex float so the value is exact rather than nearest-parsed.");
            writer.WriteLine("constexpr double overflow = 0x1.ffffffp+127;");
            writer.WriteLine();
            using (writer.Block("if (v != v)"))
            {
                writer.WriteLine("return ::std::numeric_limits<float>::quiet_NaN();");
            }

            writer.WriteLine();
            using (writer.Block("if (v >= overflow)"))
            {
                writer.WriteLine("return ::std::numeric_limits<float>::infinity();");
            }

            writer.WriteLine();
            using (writer.Block("if (v <= -overflow)"))
            {
                writer.WriteLine("return -::std::numeric_limits<float>::infinity();");
            }

            writer.WriteLine();
            writer.WriteLine("return static_cast<float>(v);");
        }

        writer.WriteLine();
    }

    private static readonly ArithmeticBehavior[] Behaviors =
    [
        ArithmeticBehavior.Wrap,
        ArithmeticBehavior.Check,
        ArithmeticBehavior.Saturate,
    ];

    /// <summary>The helper-name prefix for one overflow policy.</summary>
    public static string Stem(ArithmeticBehavior behavior) => behavior switch
    {
        ArithmeticBehavior.Wrap => "wrap",
        ArithmeticBehavior.Check => "checked",
        ArithmeticBehavior.Saturate => "sat",
        _ => throw new ArgumentOutOfRangeException(nameof(behavior), behavior, "Unhandled arithmetic behavior."),
    };

    /// <summary>Whether a helper suffix names a signed type.</summary>
    private static bool IsSigned(string suffix) => suffix[0] == 'i';

    /// <summary>
    /// Emits the four <c>*_overflows_*</c> predicates for one type.
    /// </summary>
    /// <remarks>
    /// <para>
    /// These answer "would the mathematical result leave the range?" and nothing else, so all three
    /// policies share them. Each is written in the unsigned domain, where the arithmetic itself is
    /// defined, and then tested against the signed interpretation.
    /// </para>
    /// <para>
    /// Written by hand rather than through <c>__builtin_add_overflow</c>, which MSVC does not
    /// provide. Factoring them out is what makes the three policy wrappers agree with each other by
    /// construction rather than by three separate proofs.
    /// </para>
    /// <para>
    /// Multiplication is the one that resists a one-line rule. The usual test -- multiply, divide
    /// back, compare -- is correct except that the division itself can trap on <c>MIN / -1</c>, so
    /// the two <c>-1</c> cases are answered before any division happens.
    /// </para>
    /// </remarks>
    private static void EmitOverflowPredicates(SourceWriter writer, string signed, string unsigned, string suffix)
    {
        var min = $"::std::numeric_limits<{signed}>::min()";
        var max = $"::std::numeric_limits<{signed}>::max()";

        using (writer.Block($"inline bool add_overflows_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// Overflow only when the operands share a sign that the result does not.");
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) + static_cast<{unsigned}>(b));");
                writer.WriteLine("return ((a ^ r) & (b ^ r)) < 0;");
            }
            else
            {
                writer.WriteLine($"return static_cast<{unsigned}>(a + b) < a;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool sub_overflows_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// Overflow only when the operands differ in sign and the result takes b's.");
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) - static_cast<{unsigned}>(b));");
                writer.WriteLine("return ((a ^ b) & (a ^ r)) < 0;");
            }
            else
            {
                writer.WriteLine("return a < b;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool mul_overflows_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (a == 0 || b == 0)"))
            {
                writer.WriteLine("return false;");
            }

            writer.WriteLine();

            if (IsSigned(suffix))
            {
                writer.WriteLine("// Answered before the division below, which would itself trap on MIN / -1.");
                using (writer.Block("if (a == -1)"))
                {
                    writer.WriteLine($"return b == {min};");
                }

                writer.WriteLine();
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine($"return a == {min};");
                }

                writer.WriteLine();
                writer.WriteLine(
                    $"const {signed} r = static_cast<{signed}>(static_cast<{unsigned}>(a) * static_cast<{unsigned}>(b));");
                writer.WriteLine("return r / a != b;");
            }
            else
            {
                writer.WriteLine($"return b > {max} / a;");
            }
        }

        writer.WriteLine();

        using (writer.Block($"inline bool neg_overflows_{suffix}({signed} a)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine($"return a == {min};");
            }
            else
            {
                writer.WriteLine("// Any non-zero unsigned value negates to something unrepresentable. No call");
                writer.WriteLine("// site can reach this: negating an unsigned value is PL0052.");
                writer.WriteLine("return a != 0;");
            }
        }

        writer.WriteLine();
    }

    /// <summary>Emits <c>add</c>, <c>sub</c>, or <c>mul</c> for one type under one policy.</summary>
    private static void EmitBinaryHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string name,
        string op,
        string description,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);
        var wrapped =
            $"static_cast<{signed}>(static_cast<{unsigned}>(a) {op} static_cast<{unsigned}>(b))";

        writer.WriteLine($"// {char.ToUpperInvariant(description[0])}{description[1..]}, {Describe(behavior)}.");
        using (writer.Block($"inline {signed} {stem}_{name}_{suffix}({signed} a, {signed} b)"))
        {
            if (behavior != ArithmeticBehavior.Wrap)
            {
                using (writer.Block($"if ({name}_overflows_{suffix}(a, b))"))
                {
                    writer.WriteLine(behavior == ArithmeticBehavior.Check
                        ? $"fail_overflow(\"{description}\");"
                        : SaturationBound(signed, suffix, name));
                }

                writer.WriteLine();
            }

            writer.WriteLine($"return {wrapped};");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// The clamp for an operation already established to overflow.
    /// </summary>
    /// <remarks>
    /// Derived from the operands rather than from the wrapped result. Addition overflows only when
    /// both operands share a sign, so either one names the bound; subtraction overflows away from
    /// <c>b</c>'s sign; a product's sign is the exclusive-or of its operands', neither of which
    /// can be zero here. Unsigned arithmetic can only leave the range at one end.
    /// </remarks>
    private static string SaturationBound(string signed, string suffix, string name)
    {
        var min = $"::std::numeric_limits<{signed}>::min()";
        var max = $"::std::numeric_limits<{signed}>::max()";

        if (!IsSigned(suffix))
        {
            return name == "sub" ? $"return {min};" : $"return {max};";
        }

        return name switch
        {
            "add" => $"return b > 0 ? {max} : {min};",
            "sub" => $"return b > 0 ? {min} : {max};",
            "mul" => $"return (a < 0) != (b < 0) ? {min} : {max};",
            _ => throw new ArgumentOutOfRangeException(nameof(name), name, "Not a saturating binary operation."),
        };
    }

    private static void EmitNegateHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine($"// Negation, {Describe(behavior)}.");
        using (writer.Block($"inline {signed} {stem}_neg_{suffix}({signed} a)"))
        {
            if (behavior != ArithmeticBehavior.Wrap)
            {
                using (writer.Block($"if (neg_overflows_{suffix}(a))"))
                {
                    writer.WriteLine(behavior == ArithmeticBehavior.Check
                        ? "fail_overflow(\"negation\");"
                        : $"return ::std::numeric_limits<{signed}>::max();");
                }

                writer.WriteLine();
            }

            writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the termination helper behind the checked overflow policy.
    /// </summary>
    /// <remarks>
    /// Separate from <c>fail</c> only because the two say different things: one reports a divisor
    /// that was zero, the other a result that did not fit. Both stop the process the same way and
    /// with the same exit code, so a test can pin either through <c>expect fail</c>.
    /// </remarks>
    private static void EmitFailOverflowHelper(SourceWriter writer)
    {
        writer.WriteLine("// Reached only under the checked overflow policy, where the project declared that");
        writer.WriteLine("// an unrepresentable result is not to be papered over.");
        using (writer.Block("[[noreturn]] inline void fail_overflow(const char* operation)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoLang: \", stderr);");
            writer.WriteLine("::std::fputs(operation, stderr);");
            writer.WriteLine("::std::fputs(\" overflowed\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
    }

    private static void EmitDivideOrFailHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Division that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} {stem}_div_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrFailHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Remainder that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} {stem}_mod_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback. The fallback is
    /// evaluated eagerly at the call site; ProtoLang expressions have no side effects, so this is
    /// indistinguishable from lazy evaluation.
    /// </summary>
    private static void EmitDivideOrHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Division that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} {stem}_div_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Remainder that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} {stem}_mod_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return {stem}_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitDivideHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string unsigned,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} {stem}_div_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// MIN / -1 is the one division that overflows. The -1 case is answered here,");
                writer.WriteLine("// before the divide instruction, which would otherwise trap.");
                using (writer.Block("if (b == -1)"))
                {
                    if (behavior != ArithmeticBehavior.Wrap)
                    {
                        using (writer.Block($"if (a == ::std::numeric_limits<{signed}>::min())"))
                        {
                            writer.WriteLine(behavior == ArithmeticBehavior.Check
                                ? "fail_overflow(\"division\");"
                                : $"return ::std::numeric_limits<{signed}>::max();");
                        }

                        writer.WriteLine();
                    }

                    writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a / b;");
        }

        writer.WriteLine();
    }

    private static void EmitModuloHelper(
        SourceWriter writer,
        ArithmeticBehavior behavior,
        string signed,
        string suffix)
    {
        var stem = Stem(behavior);

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} {stem}_mod_{suffix}({signed} a, {signed} b)"))
        {
            if (IsSigned(suffix))
            {
                writer.WriteLine("// MIN % -1 traps on the same instruction as the quotient, but unlike the");
                writer.WriteLine("// quotient the remainder is 0, which every type can represent. No policy");
                writer.WriteLine("// differs here.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a % b;");
        }

        writer.WriteLine();
    }

    private static string Describe(ArithmeticBehavior behavior) => behavior switch
    {
        ArithmeticBehavior.Wrap => "wrapping on overflow",
        ArithmeticBehavior.Check => "terminating the process on overflow",
        ArithmeticBehavior.Saturate => "clamping on overflow",
        _ => throw new ArgumentOutOfRangeException(nameof(behavior), behavior, "Unhandled arithmetic behavior."),
    };

    /// <summary>
    /// Exit code of a program stopped by <c>on_zero fail</c>. <c>EX_SOFTWARE</c> from
    /// <c>sysexits.h</c>, and normative: every backend reports the same code (spec 10.2.1).
    /// </summary>
    public const int FailExitCode = 70;

    /// <summary>
    /// Emits the deterministic-termination helper behind <c>on_zero fail</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Writing to stderr is the one place generated code performs I/O. Spec 20 bans I/O in method
    /// bodies; this is a fatal-error path, not behavior, and stopping with no explanation would be
    /// far harder to diagnose.
    /// </para>
    /// <para>
    /// <c>_Exit</c> rather than <c>abort</c>. <c>abort</c> raises <c>SIGABRT</c>, which means two
    /// things this needs to avoid: the default handler hands the process to the platform's crash
    /// reporter -- a dialog and a postmortem debugger prompt on Windows -- and a program that
    /// installs its own <c>SIGABRT</c> handler could <em>resume</em>, which would defeat the whole
    /// point of the clause. <c>_Exit</c> can be intercepted by nothing, runs no destructors or
    /// atexit handlers, and reports the exit code chosen here rather than a signal.
    /// </para>
    /// </remarks>
    private static void EmitFailHelper(SourceWriter writer)
    {
        writer.WriteLine("// Reached only from an 'on_zero fail' clause, where the author declared that");
        writer.WriteLine("// no substitute value is correct.");
        using (writer.Block("[[noreturn]] inline void fail(const char* operation)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoLang: \", stderr);");
            writer.WriteLine("::std::fputs(operation, stderr);");
            writer.WriteLine("::std::fputs(\" by zero\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine();
            writer.WriteLine("// Not abort(): SIGABRT is catchable, and its default handler raises a crash");
            writer.WriteLine("// report. Generated library code must not be able to do either.");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
    }

    private static void EmitDivideOrFailHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Division that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} wrap_div_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrFailHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Remainder that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} wrap_mod_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback. The fallback is
    /// evaluated eagerly at the call site; ProtoLang expressions have no side effects, so this is
    /// indistinguishable from lazy evaluation.
    /// </summary>
    private static void EmitDivideOrHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Division that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} wrap_div_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Remainder that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} wrap_mod_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitDivideHelper(
        SourceWriter writer,
        string signed,
        string unsigned,
        string suffix)
    {
        var isSigned = suffix[0] == 'i';

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} wrap_div_{suffix}({signed} a, {signed} b)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN / -1 overflows. Under wrapping semantics the result is MIN itself.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a / b;");
        }

        writer.WriteLine();
    }

    private static void EmitModuloHelper(SourceWriter writer, string signed, string suffix)
    {
        var isSigned = suffix[0] == 'i';

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} wrap_mod_{suffix}({signed} a, {signed} b)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN % -1 overflows on some targets; the wrapped result is 0.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a % b;");
        }

        writer.WriteLine();
    }
}
