namespace ProtoLang.Backend.Cpp;

/// <summary>
/// The fixed C++ support header emitted alongside generated code.
/// </summary>
/// <remarks>
/// Signed integer overflow is undefined behavior in C++, not wraparound. Compilers exploit that:
/// an optimizer is entitled to assume it never happens and delete the code that would follow.
/// ProtoLang's wrapping semantics therefore cannot be expressed as bare <c>a + b</c>; every
/// operation routes through these helpers, which perform the arithmetic in the unsigned domain
/// where modular behavior is well-defined.
/// </remarks>
public static class CppRuntime
{
    public const string FileName = "protolang_runtime.h";

    // Lazy rather than a field initializer: Build() reads static tables declared further down,
    // and static field initializers run in declaration order.
    private static readonly Lazy<string> LazySource = new(Build);

    public static string Source => LazySource.Value;

    private static string Build()
    {
        var writer = new SourceWriter("  ");

        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("//     ProtoLang C++ support header. Generated by protolangc.");
        writer.WriteLine("//     Changes to this file will be lost when the code is regenerated.");
        writer.WriteLine("// </auto-generated>");
        writer.WriteLine();
        writer.WriteLine("#ifndef PROTOLANG_RUNTIME_H_");
        writer.WriteLine("#define PROTOLANG_RUNTIME_H_");
        writer.WriteLine();
        writer.WriteLine("#include <cstdint>");
        writer.WriteLine("#include <cstdio>");
        writer.WriteLine("#include <cstdlib>");
        writer.WriteLine();
        writer.WriteLine("// Requires C++20: the conversion from an unsigned type back to the corresponding");
        writer.WriteLine("// signed type is defined as two's complement (P0907R4). Earlier standards leave that");
        writer.WriteLine("// conversion implementation-defined.");
        writer.WriteLine("static_assert(__cplusplus >= 202002L, \"ProtoLang generated code requires C++20 or later.\");");
        writer.WriteLine();

        using (writer.Block("namespace protolang_runtime"))
        {
            EmitFailHelper(writer);

            foreach (var (signed, unsigned, suffix) in IntegerTypes)
            {
                writer.WriteLine($"// --- {signed} ---");
                writer.WriteLine();

                EmitBinaryHelper(writer, "add", "+", signed, unsigned, suffix);
                EmitBinaryHelper(writer, "sub", "-", signed, unsigned, suffix);
                EmitBinaryHelper(writer, "mul", "*", signed, unsigned, suffix);
                EmitNegateHelper(writer, signed, unsigned, suffix);
                EmitDivideHelper(writer, signed, unsigned, suffix);
                EmitModuloHelper(writer, signed, suffix);
                EmitDivideOrHelper(writer, signed, suffix);
                EmitModuloOrHelper(writer, signed, suffix);
                EmitDivideOrFailHelper(writer, signed, suffix);
                EmitModuloOrFailHelper(writer, signed, suffix);
            }
        }

        writer.WriteLine();
        writer.WriteLine("#endif  // PROTOLANG_RUNTIME_H_");

        return writer.ToString();
    }

    /// <summary>(signed C++ type, unsigned C++ type, ProtoLang helper suffix).</summary>
    private static readonly (string Signed, string Unsigned, string Suffix)[] IntegerTypes =
    [
        ("::std::int32_t", "::std::uint32_t", "i32"),
        ("::std::int64_t", "::std::uint64_t", "i64"),
        ("::std::uint32_t", "::std::uint32_t", "u32"),
        ("::std::uint64_t", "::std::uint64_t", "u64"),
    ];

    private static void EmitBinaryHelper(
        SourceWriter writer,
        string name,
        string op,
        string signed,
        string unsigned,
        string suffix)
    {
        using (writer.Block($"inline {signed} wrap_{name}_{suffix}({signed} a, {signed} b)"))
        {
            writer.WriteLine(
                $"return static_cast<{signed}>(static_cast<{unsigned}>(a) {op} static_cast<{unsigned}>(b));");
        }

        writer.WriteLine();
    }

    private static void EmitNegateHelper(SourceWriter writer, string signed, string unsigned, string suffix)
    {
        using (writer.Block($"inline {signed} wrap_neg_{suffix}({signed} a)"))
        {
            writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Exit code of a program stopped by <c>on_zero fail</c>. <c>EX_SOFTWARE</c> from
    /// <c>sysexits.h</c>, and normative: every backend reports the same code (spec 10.2.1).
    /// </summary>
    public const int FailExitCode = 70;

    /// <summary>
    /// Emits the deterministic-termination helper behind <c>on_zero fail</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Writing to stderr is the one place generated code performs I/O. Spec 20 bans I/O in method
    /// bodies; this is a fatal-error path, not behavior, and stopping with no explanation would be
    /// far harder to diagnose.
    /// </para>
    /// <para>
    /// <c>_Exit</c> rather than <c>abort</c>. <c>abort</c> raises <c>SIGABRT</c>, which means two
    /// things this needs to avoid: the default handler hands the process to the platform's crash
    /// reporter -- a dialog and a postmortem debugger prompt on Windows -- and a program that
    /// installs its own <c>SIGABRT</c> handler could <em>resume</em>, which would defeat the whole
    /// point of the clause. <c>_Exit</c> can be intercepted by nothing, runs no destructors or
    /// atexit handlers, and reports the exit code chosen here rather than a signal.
    /// </para>
    /// </remarks>
    private static void EmitFailHelper(SourceWriter writer)
    {
        writer.WriteLine("// Reached only from an 'on_zero fail' clause, where the author declared that");
        writer.WriteLine("// no substitute value is correct.");
        using (writer.Block("[[noreturn]] inline void fail(const char* operation)"))
        {
            writer.WriteLine("::std::fputs(\"ProtoLang: \", stderr);");
            writer.WriteLine("::std::fputs(operation, stderr);");
            writer.WriteLine("::std::fputs(\" by zero\\n\", stderr);");
            writer.WriteLine("::std::fflush(stderr);");
            writer.WriteLine();
            writer.WriteLine("// Not abort(): SIGABRT is catchable, and its default handler raises a crash");
            writer.WriteLine("// report. Generated library code must not be able to do either.");
            writer.WriteLine($"::std::_Exit({FailExitCode});");
        }

        writer.WriteLine();
    }

    private static void EmitDivideOrFailHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Division that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} wrap_div_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"division\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrFailHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Remainder that terminates the process on a zero divisor.");
        using (writer.Block($"inline {signed} wrap_mod_or_fail_{suffix}({signed} a, {signed} b)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("fail(\"modulo\");");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    /// <summary>
    /// Emits the form used when the author supplied an <c>on_zero</c> fallback. The fallback is
    /// evaluated eagerly at the call site; ProtoLang expressions have no side effects, so this is
    /// indistinguishable from lazy evaluation.
    /// </summary>
    private static void EmitDivideOrHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Division that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} wrap_div_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_div_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitModuloOrHelper(SourceWriter writer, string signed, string suffix)
    {
        writer.WriteLine("// Remainder that yields on_zero instead of failing.");
        using (writer.Block(
            $"inline {signed} wrap_mod_or_{suffix}({signed} a, {signed} b, {signed} on_zero)"))
        {
            using (writer.Block("if (b == 0)"))
            {
                writer.WriteLine("return on_zero;");
            }

            writer.WriteLine();
            writer.WriteLine($"return wrap_mod_{suffix}(a, b);");
        }

        writer.WriteLine();
    }

    private static void EmitDivideHelper(
        SourceWriter writer,
        string signed,
        string unsigned,
        string suffix)
    {
        var isSigned = suffix[0] == 'i';

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} wrap_div_{suffix}({signed} a, {signed} b)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN / -1 overflows. Under wrapping semantics the result is MIN itself.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine($"return static_cast<{signed}>(0u - static_cast<{unsigned}>(a));");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a / b;");
        }

        writer.WriteLine();
    }

    private static void EmitModuloHelper(SourceWriter writer, string signed, string suffix)
    {
        var isSigned = suffix[0] == 'i';

        writer.WriteLine("// Reached only when the divisor is a non-zero literal, so b is never 0.");
        using (writer.Block($"inline {signed} wrap_mod_{suffix}({signed} a, {signed} b)"))
        {
            if (isSigned)
            {
                writer.WriteLine("// MIN % -1 overflows on some targets; the wrapped result is 0.");
                using (writer.Block("if (b == -1)"))
                {
                    writer.WriteLine("return 0;");
                }

                writer.WriteLine();
            }

            writer.WriteLine("return a % b;");
        }

        writer.WriteLine();
    }
}
