using System.Text;
using ProtoLang.Backend;

namespace ProtoLang.Backend.Cpp;

/// <summary>
/// The CMake project that builds and runs generated C++ ProtoLang test drivers.
/// </summary>
/// <remarks>
/// <para>
/// CMake rather than an emitted compile-and-link script, because the hard part of building
/// generated C++ is not the command line, it is the dependencies. Protobuf 4.x split Abseil and
/// <c>utf8_range</c> out of <c>libprotobuf</c>, so a correct link names libraries that vary by
/// version, platform, and whether the install is static or shared.
/// <c>find_package(Protobuf CONFIG)</c> answers all of that through the
/// <c>protobuf::libprotobuf</c> imported target, and <c>protobuf_generate</c> removes the manual
/// protoc step with it.
/// </para>
/// <para>
/// This is the same problem the repository's own harness solves by hand in
/// <c>CppTestWorkspace</c>, branching between MSVC response files and POSIX command lines and
/// naming vcpkg's Windows libraries literally.
/// </para>
/// </remarks>
public static class CppTestProject
{
    public const string FileName = "CMakeLists.txt";

    /// <summary>The CMake target the generated protobuf message classes are compiled into.</summary>
    private const string SchemaTarget = "protolang_protos";

    public static string Build(ScaffoldOptions options)
    {
        var builder = new StringBuilder();

        builder.AppendLine("# Generated by protolangc. Builds and runs ProtoLang tests for this project's");
        builder.AppendLine("# generated C++ behavior. Changes to this file will be lost when it is regenerated.");
        builder.AppendLine("#");
        builder.AppendLine("#   cmake -S . -B build");
        builder.AppendLine("#   cmake --build build --config Debug");
        builder.AppendLine("#   ctest --test-dir build -C Debug --output-on-failure");
        builder.AppendLine("#");
        builder.AppendLine("# The config arguments are required by multi-config generators such as Visual");
        builder.AppendLine("# Studio, and ignored by single-config ones, so they are always safe to pass.");
        builder.AppendLine("#");
        builder.AppendLine("# A protobuf install CMake cannot find on its own is named at configure time:");
        builder.AppendLine("#   cmake -S . -B build -DCMAKE_PREFIX_PATH=/path/to/protobuf");
        builder.AppendLine();
        builder.AppendLine("cmake_minimum_required(VERSION 3.20)");
        builder.AppendLine("project(protolang_tests CXX)");
        builder.AppendLine();
        builder.AppendLine("set(CMAKE_CXX_STANDARD 20)");
        builder.AppendLine("set(CMAKE_CXX_STANDARD_REQUIRED ON)");
        builder.AppendLine();
        builder.AppendLine("# Single-config generators build nothing useful without a build type, and a test");
        builder.AppendLine("# project has no reason to make the caller supply one.");
        builder.AppendLine("if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)");
        builder.AppendLine("    set(CMAKE_BUILD_TYPE Debug)");
        builder.AppendLine("endif()");
        builder.AppendLine();
        builder.AppendLine("# MSVC reports __cplusplus as 199711L regardless of /std: unless asked not to, and");
        builder.AppendLine("# the generated runtime header static_asserts on __cplusplus. Without this the build");
        builder.AppendLine("# fails claiming C++20 is unavailable while compiling as C++20.");
        builder.AppendLine("if(MSVC)");
        builder.AppendLine("    add_compile_options(/Zc:__cplusplus)");
        builder.AppendLine("endif()");
        builder.AppendLine();
        builder.AppendLine("# CONFIG mode, so protobuf::libprotobuf carries its Abseil and utf8_range");
        builder.AppendLine("# dependencies transitively instead of this file having to name them.");
        builder.AppendLine("find_package(Protobuf CONFIG REQUIRED)");
        builder.AppendLine();
        builder.AppendLine("enable_testing()");
        builder.AppendLine();

        // A source that extends only well-known types leaves nothing to generate: those ship
        // precompiled in libprotobuf and are filtered out of the schema list. Emitting the target
        // anyway would declare a library with no sources and hand protobuf_generate no .proto
        // files, which is a configure-time error rather than something the build survives.
        if (options.ProtoFiles.Count > 0)
        {
            EmitSchemaTarget(builder, options);
        }

        // Only the C++ sources: a test backend may emit support files alongside its drivers, and
        // an executable per support file would neither compile nor mean anything.
        foreach (var driver in options.TestSourceFileNames.Where(IsCppSource))
        {
            EmitDriver(builder, options, driver);
        }

        return builder.ToString();
    }

    private static void EmitSchemaTarget(StringBuilder builder, ScaffoldOptions options)
    {
        builder.AppendLine("# Protobuf message classes, generated at build time. protobuf_generate writes them");
        builder.AppendLine("# into the binary directory, which is why that is an include root below.");
        builder.AppendLine($"add_library({SchemaTarget} STATIC");

        foreach (var proto in options.ProtoFiles)
        {
            builder.AppendLine($"    {Quote(Join(proto.ProtoRoot, proto.RelativePath))}");
        }

        builder.AppendLine(")");
        builder.AppendLine();
        builder.AppendLine($"target_link_libraries({SchemaTarget} PUBLIC protobuf::libprotobuf)");
        builder.AppendLine(
            $"target_include_directories({SchemaTarget} PUBLIC \"${{CMAKE_CURRENT_BINARY_DIR}}\")");
        builder.AppendLine();
        builder.AppendLine("protobuf_generate(");
        builder.AppendLine($"    TARGET {SchemaTarget}");
        builder.AppendLine("    IMPORT_DIRS");

        // Distinct roots, in the order they were given: protoc resolves an import against the first
        // root that contains it, so the order is not incidental.
        foreach (var root in options.ProtoFiles
            .Select(proto => Normalize(proto.ProtoRoot))
            .Distinct(StringComparer.Ordinal))
        {
            builder.AppendLine($"        {Quote(root.Length == 0 ? "." : root)}");
        }

        // Last, so a schema vendoring its own copy still wins. A schema that imports a well-known
        // type needs those resolvable here too, and protoc only carries them internally from
        // version 33 on -- older ones have to be handed the directory protobuf installs them in.
        builder.AppendLine("        \"${Protobuf_INCLUDE_DIRS}\"");
        builder.AppendLine("    PROTOC_OUT_DIR \"${CMAKE_CURRENT_BINARY_DIR}\"");
        builder.AppendLine(")");
        builder.AppendLine();
    }

    private static void EmitDriver(StringBuilder builder, ScaffoldOptions options, string driver)
    {
        var target = TargetName(driver);
        var hasSchemaTarget = options.ProtoFiles.Count > 0;

        builder.AppendLine($"add_executable({target} {Quote(Normalize(driver))})");
        builder.AppendLine();

        if (hasSchemaTarget)
        {
            builder.AppendLine("# Three include roots, all load-bearing: this directory for the driver, the behavior");
            builder.AppendLine("# directory because the driver includes its ProtoLang header unqualified, and the");
            builder.AppendLine($"# binary directory, which {SchemaTarget} supplies for the generated .pb.h files.");
        }
        else
        {
            builder.AppendLine("# Two include roots: this directory for the driver, and the behavior directory");
            builder.AppendLine("# because the driver includes its ProtoLang header unqualified. Nothing is");
            builder.AppendLine("# generated here, so there is no binary directory to add; the well-known type");
            builder.AppendLine("# headers arrive with protobuf::libprotobuf.");
        }

        builder.AppendLine($"target_include_directories({target} PRIVATE");
        builder.AppendLine("    \"${CMAKE_CURRENT_SOURCE_DIR}\"");
        builder.AppendLine($"    {Quote(BehaviorInclude(options.BehaviorDirectory))}");
        builder.AppendLine(")");
        builder.AppendLine();
        builder.AppendLine(
            $"target_link_libraries({target} PRIVATE "
            + (hasSchemaTarget ? SchemaTarget : "protobuf::libprotobuf")
            + ")");
        builder.AppendLine();
        builder.AppendLine("# The driver runs every test it was generated with and returns non-zero if any");
        builder.AppendLine("# failed, so one ctest entry per driver reports the whole file.");
        builder.AppendLine($"add_test(NAME {target} COMMAND {target})");
        builder.AppendLine();
        builder.AppendLine("# On Windows the protobuf and Abseil DLLs have to sit beside the executable. This");
        builder.AppendLine("# expands to nothing when everything is linked statically or on platforms that use");
        builder.AppendLine("# an rpath, so it is unconditional.");
        builder.AppendLine($"add_custom_command(TARGET {target} POST_BUILD");
        builder.AppendLine("    COMMAND \"${CMAKE_COMMAND}\" -E copy -t");
        builder.AppendLine($"            \"$<TARGET_FILE_DIR:{target}>\" \"$<TARGET_RUNTIME_DLLS:{target}>\"");
        builder.AppendLine("    COMMAND_EXPAND_LISTS");
        builder.AppendLine(")");
        builder.AppendLine();
    }

    /// <summary>
    /// The behavior directory as an include root. A relative path is anchored to the source
    /// directory rather than left bare, because a bare relative include directory is resolved
    /// against the build directory by some generators.
    /// </summary>
    private static string BehaviorInclude(string behaviorDirectory)
    {
        var normalized = Normalize(behaviorDirectory);
        return normalized.Length == 0 || normalized == "."
            ? "${CMAKE_CURRENT_SOURCE_DIR}"
            : "${CMAKE_CURRENT_SOURCE_DIR}/" + normalized.TrimEnd('/');
    }

    /// <summary>
    /// A CMake target name for a driver file. Target names share one flat namespace and accept a
    /// restricted character set, so everything outside it becomes an underscore.
    /// </summary>
    private static string TargetName(string driver)
    {
        var stem = Path.GetFileName(driver);
        foreach (var suffix in new[] { ".tests.cc", ".cc", ".cpp" })
        {
            if (stem.EndsWith(suffix, StringComparison.Ordinal))
            {
                stem = stem[..^suffix.Length];
                break;
            }
        }

        var builder = new StringBuilder();
        foreach (var c in stem)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return builder.Length == 0 ? "protolang_tests" : builder.ToString() + "_tests";
    }

    private static bool IsCppSource(string fileName)
        => fileName.EndsWith(".cc", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".cpp", StringComparison.OrdinalIgnoreCase);

    private static string Normalize(string path) => path.Replace('\\', '/');

    private static string Join(string directory, string relative)
    {
        var normalized = Normalize(directory);
        return normalized.Length == 0 || normalized == "."
            ? Normalize(relative)
            : normalized.TrimEnd('/') + "/" + Normalize(relative);
    }

    /// <summary>
    /// Quotes a CMake argument. Backslashes and quotes are the only characters that need escaping
    /// inside a quoted argument, and paths are normalized to forward slashes before they get here.
    /// </summary>
    private static string Quote(string value)
        => "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
